### ISSUE TITLE
Conflict with apparently require/react.js [BUG]

### ISSUE THREAD

**Issue by flacle** [Typeform/embed#56] opened 2020-07-17 13:35 UTC
**Describe the bug**
Typeform Embed is breaking our site after apparent release https://github.com/Typeform/embed/releases/tag/v0.21.4 - because last good response on our survey was on June 19 2020.

**To Reproduce**
1. Use the latest version of Typeform
2. Use require.js version 2.3.5

**Expected behavior**
No issues with prior June 20.

**Current behavior**
Receiving current make error at **require.min.js:5**:
`Uncaught Error: Mismatched anonymous define() module: function(){return r={},o.m=n=[function(e,t,n){"use strict";n.d(t,"l",function(){return q}),n.d(t,"i",function(){return V}),n.d(t,"k",function(){return K}),n.d(t,"j",function()...`
    ...http://requirejs.org/docs/errors.html#mismatch
        at makeError (VM39202 require.min.js:5)
        at v (VM39202 require.min.js:5)
        at VM39202 require.min.js:5

Site works as expected when removing the survey.

**Desktop (please complete the following information):**
 - Embed SDK Version [latest from https://embed.typeform.com/embed.js]

**Additional context**
Production environment

**Comment by mathio** [comment] 2020-07-20 14:02
Hello @flacle !

I tried to embed a typeform using RequireJS v2.3.5, React v16 and embed library (both v0.21.4 and latest) and it works fine. 

Here is my test: https://glitch.com/~embed-requirejs

Can you please provide a minimal example that is causing your issue?

**Comment by Adam314** [comment] 2020-07-31 12:12
Hello @mathio. I have the same problem with Typeform. I'm embedding a Typeform button which should open form on right panel. I'm getting exactly the same error. Here's the button's code (I removed the form ID from URL):
`<a class="typeform-share button" href="https://form.typeform.com/to/REMOVED_ID" data-mode="drawer_right" style="display:inline-block;text-decoration:none;background-color:#1B75BB;color:white;cursor:pointer;font-family:Helvetica,Arial,sans-serif;font-size:20px;line-height:50px;text-align:center;margin:0;height:50px;padding:0px 33px;border-radius:25px;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:bold;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;" target="_blank">Give us some feedback! </a> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm_share", b="https://embed.typeform.com/"; if(!gi.call(d,id)){ js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>  </div>`

The page is generated apidoc (https://apidocjs.com/) where I just put the button code in a template file.

What would be the simplest way to get rid of this error?

**Comment by mathio** [comment] 2020-08-03 14:00
Hello @Adam314.

I believe that if you are using `require.js` you need to load the embed library vie `require.js`:

```
<script src="https://embed.typeform.com/embed.js"></script>
<a class="typeform-share" href="https://form.typeform.com/to/jAJ5qj" data-mode="drawer_right" target="_blank">Give us some feedback! </a>
```

It looks like `require.js` does not support using a code snippet from the Typeform share page directly because [it loads the embed library dynamically](https://requirejs.org/docs/errors.html#mismatch)).

@flacle was your issue caused by using the embed snippet from share page too?

**Comment by Adam314** [comment] 2020-08-03 17:52
@mathio Thank you! That did the trick.

**Comment by mathio** [comment] 2020-08-06 12:51
Closing as resolved. If you have more problems feel free to open a new issue.

**Closed by mathio** 2020-08-06 12:51 UTC
Labels: bug
