### ISSUE TITLE
onSubmit option does not appear to trigger

### ISSUE THREAD

**Issue by willitt** [Typeform/embed#454] opened 2022-02-04 20:14 UTC
Hi,
I noticed that recently the onSubmit function option does not appear to be being called for either the @typeform/embed or @typeform/embed-react libraries when a user completes the Typeform. Below I've attached a couple of codepen demos of the issue for both libraries:
https://codepen.io/shoelaceross/pen/GROjBOj - For @typeform/embed-react
https://codepen.io/shoelaceross/pen/VwrKBXv - For @typeform/embed

Please let me know if I've missed something obvious or if you need any more info!

**Comment by mathio** [comment] 2022-02-04 20:16
Duplicate of #453.

**Closed by mathio** 2022-02-04 20:16 UTC
